# Generated by Django 2.0.2 on 2018-02-28 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('cedula', models.CharField(max_length=13, unique=True)),
                ('fechaNacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('ciudad', models.CharField(max_length=45)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='Masculino', max_length=1)),
                ('talla', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L')], default='XS', max_length=2)),
                ('tipoDeSangre', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=3)),
                ('alergias', models.CharField(max_length=45)),
                ('club', models.BooleanField()),
                ('clubNombre', models.CharField(blank=True, max_length=45)),
                ('nombreContactoEmergencia', models.CharField(max_length=45)),
                ('telefonoContactoEmergencia', models.CharField(max_length=15)),
                ('Pago', models.NullBooleanField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrera.Categoria')),
            ],
        ),
    ]
